ghost_blog:
    resource: "@GhostBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix: /_terminal

ghost_console:
    resource: "@GhostBlogBundle/Resources/config/console.yml"
    prefix: /console/
